### ISSUE TITLE
CWL: shorten job names

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#3235] opened 2020-09-23 06:50 UTC
"We could also try and update the job naming for CWL jobs to include fewer UUIDs, because I'm not sure they really help anyone for debugging." https://github.com/DataBiosphere/toil/issues/3226#issuecomment-695022213

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-666)
┆Issue Number: TOIL-666

**Comment by DailyDreaming** [comment] 2020-11-30 23:39
Hmmm... I think that #3230 may have addressed this.  Exported files don't seem to have insanely long paths anymore from what I can see and job names tend to look something like: `Job('CWLJob' wc -l TemporaryID(49e21741-09c2-469f-87b8-3a01eee945ee))`

I'm going to close this since I think that this is resolved.  Please reopen if this is still an issue (though if reopened, also please include a minimal reproducible example of a long job name and maybe a suggestion of a more preferable name if so!).

**Closed by DailyDreaming** 2020-11-30 23:39 UTC
Labels: cwl, enhancement, good first issue, ready
