### ISSUE TITLE
Job failing

### ISSUE THREAD

**Issue by claudiodonati** [DataBiosphere/toil#2474] opened 2018-11-19 09:55 UTC
I am running toil to run a pipeline over a list of files. My jobs keep crashing randomly (i.e. not al files crash and if I process the same files twice the ones that crash are not always the same). 
Going through the stderr I find the following lines:

WARNING:toil.leader:e/h/job52Acup    (ERR): mkfifo(/tmp/1.inpipe1) failed.
WARNING:toil.leader:e/h/job52Acup    Exiting now ...
WARNING:toil.leader:e/h/job52Acup    [job bowtie2.cwl] completed permanentFail
WARNING:toil.leader:e/h/job52Acup    Traceback (most recent call last):
WARNING:toil.leader:e/h/job52Acup      File "/fem-homes/claudio.donati/CWL/venv/local/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript
WARNING:toil.leader:e/h/job52Acup        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:e/h/job52Acup      File "/fem-homes/claudio.donati/CWL/venv/local/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
WARNING:toil.leader:e/h/job52Acup        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:e/h/job52Acup      File "/fem-homes/claudio.donati/CWL/venv/local/lib/python2.7/site-packages/toil/job.py", line 1296, in _run
WARNING:toil.leader:e/h/job52Acup        return self.run(fileStore)
WARNING:toil.leader:e/h/job52Acup      File "/fem-homes/claudio.donati/CWL/venv/local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 567, in run
WARNING:toil.leader:e/h/job52Acup        raise cwltool.errors.WorkflowException(status)
WARNING:toil.leader:e/h/job52Acup    WorkflowException: permanentFail
WARNING:toil.leader:e/h/job52Acup    ERROR:toil.worker:Exiting the worker because of a failed job on host vm-micca.research.cri
WARNING:toil.leader:e/h/job52Acup    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///fem-homes/claudio.donati/CWL/Strainest/Prove/strainest_web_pa

Any hint of what the problem might be?

Thanks,

Claudio

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-66)
┆Issue Number: TOIL-66

**Comment by mr-c** [comment] 2018-11-19 10:55
Hello Claudio. Are you running on a single machine, or using a  a batch scheduler?

What version of Toil are you using?

**Comment by claudiodonati** [comment] 2018-11-19 13:53
Hi Michael,

in this case I am running several independent cwl jobs using a batch scheduler (htcondor)

the sh command file is:

#!/bin/bash
source /home/claudio.donati/CWL/venv/bin/activate
export TMPDIR=/home/claudio.donati/CWL/Strainest/Prove/tmp
toil-cwl-runner --workDir /home/claudio.donati/CWL/Strainest/Prove/tmp --defaultMemory 16.0G --defaultDisk 100.0G --maxDisk 300.0G strainest_web_pack.cwl --reference_basename map_align --reference_dir "/home/claudio.donati/CWL/Strainest/S_salivarius/Streptococcus_Salivarius" --strainest_est_dgrp "/home/claudio.donati/CWL/Strainest/S_salivarius/Streptococcus_Salivarius/snv.txt" --input $1

These are submitted to condor though the following cmd file 
Executable = /home/claudio.donati/CWL/Strainest/Prove/comando_toil.sh
log = job.log
output = job.out
error = job.err

Arguments =  ERR589346
queue
Arguments =  ERR589347
queue
Arguments =  ERR589348
queue
....

Toil version:
(venv) claudio.donati@vm-micca>toil-cwl-runner --version
3.18.0

**Comment by mr-c** [comment] 2018-11-19 16:02
Thank you Claudio for the update. Looks like you are having htcondor run Toil in a single job, instead of Toil emitting htcondor jobs: `pip install toil[cwl,htcondor]` & `toil-cwl-runner --batchSystem HTCondor`

Since you are running in a single node, perhaps you can try with the CWL reference runner?

**Comment by claudiodonati** [comment] 2018-11-20 08:02
Yes, I am not using array jobs because, as I mentioned in an earlier post, I want temp files to be deleted as soon as they are not needed any more. If I let toil submit to htcondor the temp files will stay on my disk until the end, and I will quickly run out of disk space. Besides, I will see outputs only at the end, and this is not what I want. I think these two features will need to be introduced if you want to use toil array jobs in a production environment.

I am just rerunning my job using the reference runner. I'l keep you updated. 

Thanks for your help.

**Comment by claudiodonati** [comment] 2018-11-21 07:43
Just a quick update: my job completed without error using the reference runner.

**Comment by DailyDreaming** [comment] 2021-03-17 16:53
Closing since this has not been addressed in a long time.  If this is still  an error, please comment and we'll attempt to reproduce and run this.

**Closed by DailyDreaming** 2021-03-17 16:53 UTC
Labels: roadmap
