### ISSUE TITLE
[Intern] Appropriate error when AWS-stored key has passphrase on it.

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2243] opened 2018-06-12 05:04 UTC
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-267)
┆Issue Number: TOIL-267

**Comment by DailyDreaming** [comment] 2020-04-15 22:20
Duplicate of https://github.com/DataBiosphere/toil/issues/2006 .

**Closed by DailyDreaming** 2020-04-15 22:20 UTC
