### ISSUE TITLE
Google jobstore needs work.

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2413] opened 2018-10-14 06:19 UTC
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-289)
┆Issue Number: TOIL-289

**Comment by DailyDreaming** [comment] 2020-04-15 22:57
Duplicate of #2098 and #2203.

**Closed by DailyDreaming** 2020-04-15 22:57 UTC
