### ISSUE TITLE
improve output file copy performance

### ISSUE THREAD

**Issue by liuxf09** [DataBiosphere/toil#2224] opened 2018-05-22 17:06 UTC
For `fileJobStore`, both `writeFile` (from local to jobStore) and `_exportFile` (from jobStore to outdir) uses `shutil.copyfile`. The performance can be improved if it is changed to use `hard link` if `hard link` applies.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-257)
┆Issue Number: TOIL-257

**Comment by cricketsloan** [comment] 2019-05-16 20:42
➤ Adam Novak commented:

I’m going to close this as a duplicate of https://github.com/DataBiosphere/toil/issues/2551 ( https://github.com/DataBiosphere/toil/issues/2551 ).

We would like to rework our copying and linking system completely, but it depends on adjusting our caching logic to not have Strong Opinions about how many hardlinks any given file should have.

**Closed** 2019-05-16 20:44 UTC
