### ISSUE TITLE
Toil-CWL 5.11.0 missing 'toolpath_object'

### ISSUE THREAD

**Issue by douglowe** [DataBiosphere/toil#4520] opened 2023-07-03 10:23 UTC
I'm trying to run a workflow with Toil 5.11.0, which ran previously with an older version of Toil, but am getting an error I can't work out:
```
Log from job "'CWLWorkflow' wps_workflow.cwl kind-CWLWorkflow/instance-k0cn30eu v6" follows:
=========>
	[2023-07-03T11:17:56+0100] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2023-07-03T11:17:56+0100] [MainThread] [I] [toil] Running Toil version 5.11.0-9a04dabb36d6ab13ed1ac7c711dbdc8c71724dc9 on host ln03.
	[2023-07-03T11:17:56+0100] [MainThread] [I] [toil.worker] Working on job 'CWLWorkflow' wps_workflow.cwl kind-CWLWorkflow/instance-k0cn30eu v4
	Traceback (most recent call last):
	  File "/work/n02/n02/lowe/miniconda3/envs/toil5.11.0/lib/python3.10/site-packages/toil/worker.py", line 377, in workerScript
	    job = Job.loadJob(jobStore, jobDesc)
	  File "/work/n02/n02/lowe/miniconda3/envs/toil5.11.0/lib/python3.10/site-packages/toil/job.py", line 2659, in loadJob
	    job = cls._unpickle(userModule, fileHandle, requireInstanceOf=Job)
	  File "/work/n02/n02/lowe/miniconda3/envs/toil5.11.0/lib/python3.10/site-packages/toil/job.py", line 2281, in _unpickle
	    runnable = unpickler.load()
	TypeError: __init__() missing required argument 'toolpath_object' (pos 1)
	[2023-07-03T11:17:56+0100] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host ln03
<=========
```

Toil 5.11.0 will run a single tool, described by a CWL tool descriptor, but doesn't seem to want to run a full workflow. Is there a new flag I'm missing?

My conda environment is:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
addict                    2.4.0              pyhd8ed1ab_2    conda-forge
aiohttp                   3.8.4           py310h2372a71_1    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
annotated-types           0.5.0              pyhd8ed1ab_0    conda-forge
apache-libcloud           2.8.1                      py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argcomplete               3.1.1              pyhd8ed1ab_0    conda-forge
asn1crypto                1.5.1              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
atk-1.0                   2.38.0               hd4edc92_1    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
bagit                     1.8.1              pyhd8ed1ab_0    conda-forge
black                     23.3.0          py310hff52083_1    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blessed                   1.19.1          py310hff52083_1    conda-forge
blinker                   1.6.2              pyhd8ed1ab_0    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
boost                     1.78.0          py310hc4a4660_4    conda-forge
boost-cpp                 1.78.0               h6582d0a_3    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
cachecontrol              0.13.0             pyhd8ed1ab_0    conda-forge
cachetools                5.3.1              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            hbbf8b49_1016    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
cheetah3                  3.2.6.post2     py310h5764c6d_3    conda-forge
click                     8.1.3           py310hff52083_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
coloredlogs               15.0.1          py310hff52083_2    conda-forge
conda                     23.5.0          py310hff52083_1    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.8.0              pyhd8ed1ab_0    conda-forge
cryptography              41.0.1          py310h75e40e8_0    conda-forge
cwl-upgrader              1.2.8              pyhd8ed1ab_0    conda-forge
cwl-utils                 0.28               pyh1d7be83_0    conda-forge
cwlformat                 2022.02.18         pyhd8ed1ab_0    conda-forge
cwltool                   3.1.20230425144158 py310h1c83d0b_0    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docker-py                 5.0.3           py310hff52083_2    conda-forge
docker-pycreds            0.4.0                      py_0    conda-forge
docutils                  0.20.1          py310hff52083_0    conda-forge
enlighten                 1.11.2             pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
filelock                  3.12.2             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
frozenlist                1.3.3           py310h5764c6d_0    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
galaxy-containers         22.1.1             pyhd8ed1ab_0    conda-forge
galaxy-tool-util          22.1.5             pyhd8ed1ab_0    conda-forge
galaxy-util               22.1.1             pyhd8ed1ab_0    conda-forge
gdk-pixbuf                2.42.10              h6b639ba_2    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
google-api-core           2.11.1             pyhd8ed1ab_0    conda-forge
google-auth               2.21.0             pyh1a96a4e_0    conda-forge
google-cloud-core         2.3.2              pyhd8ed1ab_0    conda-forge
google-cloud-storage      2.8.0              pyh1a96a4e_0    conda-forge
google-crc32c             1.1.2           py310he8fe98e_4    conda-forge
google-resumable-media    2.5.0              pyhd8ed1ab_0    conda-forge
googleapis-common-protos  1.59.1             pyhd8ed1ab_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.50.0               h5abf519_3    conda-forge
grpcio                    1.56.0          py310h1b8f574_2    conda-forge
gsoap                     2.8.123              h8dc497d_0    conda-forge
gtk2                      2.24.33              h90689f9_2    conda-forge
gts                       0.7.6                h977cf35_4    conda-forge
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
htcondor-classads         10.3.1               he155508_1    conda-forge
humanfriendly             10.0            py310hff52083_4    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.7.0              pyha770c72_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
isodate                   0.6.1              pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230125.3      cxx17_h59595ed_0    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libcondor_utils           10.3.1               hd75029c_1    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.1.2                h409715c_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgd                     2.3.3                hfa28ad5_6    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libglib                   2.76.3               hebfc3b9_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libgrpc                   1.56.0               h3905398_2    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               4.23.3               hd1fb520_0    conda-forge
librsvg                   2.56.1               h98fae49_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libtool                   2.4.7                h27087fc_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libwebp                   1.3.1                hbf2b3c1_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxml2                   2.11.4               h0d562d8_0    conda-forge
libxslt                   1.1.37               h0054252_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lxml                      4.9.2           py310h9b7343a_1    conda-forge
markupsafe                2.1.3           py310h2372a71_0    conda-forge
mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.5           py310hdf3cbec_0    conda-forge
multidict                 6.0.4           py310h1fa729e_0    conda-forge
munge                     0.5.13               h1c5bbd1_1    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
networkx                  2.8.8              pyhd8ed1ab_0    conda-forge
nodejs                    18.16.1              hf52ce11_0    conda-forge
numpy                     1.25.0          py310ha4c1d20_0    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
openssl                   3.1.1                hd590300_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pango                     1.50.14              heaa33ce_1    conda-forge
pathspec                  0.11.1             pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
platformdirs              3.8.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.2.0              pyhd8ed1ab_0    conda-forge
prefixed                  0.7.0              pyhd8ed1ab_0    conda-forge
protobuf                  4.23.3          py310hb875b13_0    conda-forge
prov                      1.5.1                      py_1    conda-forge
psutil                    5.9.5           py310h1fa729e_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycosat                   0.6.4           py310h5764c6d_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodome              3.18.0          py310hb0f0acc_0    conda-forge
pydantic                  2.0             py310h2372a71_0    conda-forge
pydantic-core             2.0.1           py310hcb5633a_0    conda-forge
pydot                     1.4.2           py310hff52083_3    conda-forge
pydotplus                 2.0.2              pyhaef67bd_5    conda-forge
pyjwt                     2.7.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0           py310h5764c6d_2    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.0              pyhd8ed1ab_0    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pysocks                   1.7.1           py310hff52083_5    conda-forge
python                    3.10.12         hd12c33a_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-htcondor           10.3.1          py310h96428ee_1    conda-forge
python-kubernetes         21.7.0             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h5764c6d_5    conda-forge
rdflib                    6.3.2              pyhd8ed1ab_0    conda-forge
re2                       2023.03.02           h8c504da_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
repoze.lru                0.7                        py_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
routes                    2.5.1              pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21         py310h1fa729e_3    conda-forge
ruamel.yaml.clib          0.2.7           py310h1fa729e_1    conda-forge
schema-salad              8.4.20230606143604 py310h2372a71_0    conda-forge
scitokens-cpp             0.7.1                hf3971a6_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
shellescape               3.4.1                      py_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.42.0               h2c6b66d_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toil                      5.11.0             pyhdfd78af_0    bioconda
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
voms                      2.1.0rc3             h25bd2b9_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.6.1              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4           py310hff52083_7    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.9.2           py310h2372a71_0    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zipstream-new             1.1.8              pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstandard                 0.19.0          py310h1275a96_2    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1364)
┆Issue Number: TOIL-1364

**Comment by adamnovak** [comment] 2023-07-03 16:04
I don't think there's a new flag, and [5.11 passed the CWL conformance tests](https://ucsc-ci.com/databiosphere/toil/-/jobs/44430) that test whether workflows can run, so at least in some places it can run a CWL workflow.

This sounds like a thing that could possibly happen if the leader node and the worker nodes are not using the exact same version of `cwltool`; is it possible that that is the case for you?

**Comment by adamnovak** [comment] 2023-07-03 16:11
I just checked, and I was able to run a CWL workflow on Toil 5.11 like this:

```
    virtualenv test_venv
    . test_venv/bin/activate
    pip install 'toil[cwl]==5.11.0'

    curl -O https://raw.githubusercontent.com/DataBiosphere/toil/master/src/toil/test/cwl/conditional_wf.cwl
    curl -O https://raw.githubusercontent.com/DataBiosphere/toil/master/src/toil/test/cwl/echo.cwl
    echo '{"sleep": 3, "message": "hello"}' >conditional_wf.yaml

    toil-cwl-runner conditional_wf.cwl conditional_wf.yaml
```

This runs a simple workflow with a conditional and with one CommandLineTool task that actually executes.

Are you able to run that workflow @douglowe? Is there anything importantly different about your environment versus the one I set up when I do this?

**Comment by douglowe** [comment] 2023-07-03 16:37
Thanks for getting back to me Adam.

I have tried your workflow - it gives me the same error for my (mamba / conda) installed version of toil 5.11.0.

I've tried installing toil using virtualenv and pip, however, and the workflow is fine. So perhaps there is something in the conda install process which is messing things up - if something is precompiled on the conda platform, maybe there's a clash with the package which is installed locally for me?

FYI - this is my installed conda/pip environment:
```
(test_venv) (pip) lowe@ln02:~/test_toil> conda list
# packages in environment at /work/n02/n02/lowe/miniconda3/envs/pip:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
distlib                   0.3.6              pyhd8ed1ab_0    conda-forge
filelock                  3.12.2             pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
openssl                   3.1.1                hd590300_1    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
platformdirs              3.8.0              pyhd8ed1ab_0    conda-forge
python                    3.11.4          hab00c5b_0_cpython    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
virtualenv                20.23.1            pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
(test_venv) (pip) lowe@ln02:~/test_toil> pip list
Package                 Version
----------------------- ------------------
addict                  2.4.0
argcomplete             3.1.1
attrs                   23.1.0
bagit                   1.8.1
bleach                  6.0.0
blessed                 1.20.0
boltons                 23.0.0
CacheControl            0.13.1
certifi                 2023.5.7
charset-normalizer      3.1.0
coloredlogs             15.0.1
conda_package_streaming 0.8.0
cwl-upgrader            1.2.8
cwl-utils               0.28
cwltool                 3.1.20230425144158
dill                    0.3.6
docker                  5.0.3
docutils                0.20.1
enlighten               1.11.2
filelock                3.12.2
future                  0.18.3
galaxy-tool-util        23.0.4
galaxy-util             23.0.4
humanfriendly           10.0
idna                    3.4
importlib-resources     5.12.0
isodate                 0.6.1
lxml                    4.9.2
MarkupSafe              2.1.3
mistune                 2.0.5
msgpack                 1.0.5
mypy-extensions         1.0.0
networkx                2.8.8
packaging               21.3
pip                     23.1.2
prefixed                0.7.0
prov                    1.5.1
psutil                  5.9.5
py-tes                  0.4.2
pydantic                1.10.10
pydot                   1.4.2
pyparsing               3.1.0
Pypubsub                4.0.3
python-dateutil         2.8.2
pytz                    2023.3
PyYAML                  6.0
rdflib                  6.3.2
repoze.lru              0.7
requests                2.31.0
Routes                  2.5.1
ruamel.yaml             0.17.21
ruamel.yaml.clib        0.2.7
schema-salad            8.4.20230606143604
setuptools              67.8.0
shellescape             3.8.1
six                     1.16.0
sortedcontainers        2.4.0
toil                    5.11.0
typing_extensions       4.7.1
urllib3                 1.26.16
wcwidth                 0.2.6
webencodings            0.5.1
websocket-client        1.6.1
wheel                   0.40.0
zipstream-new           1.1.8
zstandard               0.21.0

```

**Comment by adamnovak** [comment] 2023-07-06 17:45
We don't actually do the Conda packaging for Toil as part of the Toil project, and I don't think I have enough experience using Conda to be much help here. Maybe @mr-c knows something about how Conda packages cwltool? Or maybe @DailyDreaming knows of something we did for the 5.10 release that we didn't do for the 5.11 release that makes the Conda work? Maybe something to do with the deprecated egg that uploaded for 5.11?

Or is Conda getting the package straight from PyPI and still getting a broken envrionment? @douglowe how specifically are you managing to set up the broken environment?

**Comment by mr-c** [comment] 2023-07-19 12:40
Yes, I updated the Toil packaging for 5.11.0 over at https://github.com/bioconda/bioconda-recipes/pull/41533/files

I can confirm the error using a fresh install `mamba create -n toil-5.11-test2 toil==5.11.0 enlighten` and then the test case in  https://github.com/DataBiosphere/toil/issues/4520#issuecomment-1618804096

**Comment by mr-c** [comment] 2023-07-19 17:21
Okay, in conda we are making a binary wheel for `cwltool`; and `Workflow` was set to be pickle-able. Additionally `bioconda` doesn't run tests when building packages, so this was missed. I'll see about moving the `toil` conda package to https://github.com/conda-forge/ where they do run more tests

**Comment by adamnovak** [comment] 2023-12-14 18:07
It looks like this was fixed on the Conda/cwltool side.

**Closed by adamnovak** 2023-12-14 18:07 UTC
