### ISSUE TITLE
Optional param passed through subworkflow with default causes error after 3.18 upgrade

### ISSUE THREAD

**Issue by ionox0** [DataBiosphere/toil#2512] opened 2019-01-21 17:02 UTC
I mentioned this on biostars [here](https://www.biostars.org/p/359481/), I believe it was introduced since 3.15.

### Expected result
Default should be used when parameter is not supplied, even when passed through subworkflow. 

### Actual result
When an optional parameter that is listed in both a workflow and a subworkflow is omitted and there is a default for that parameter there is an error

### Versions
toil --version: `3.18.0`
cwltool --version `1.0.20180820141117`

### Example
workflow.cwl

```
cwlVersion: v1.0
class: Workflow
requirements:
  SubworkflowFeatureRequirement: {}

inputs: []

outputs: []

steps:
  step_without_the_param:
    run: ./subworkflow.cwl
    in: []
    out: []
```

subworkflow.cwl

```
cwlVersion: v1.0
class: Workflow

inputs:
  one: boolean?
outputs: []

steps:
  one:
    run: ./tool.cwl
    in:
      one: one
    out: []
```

tool.cwl

```
cwlVersion: v1.0
class: CommandLineTool
requirements:
  InlineJavascriptRequirement: {}

baseCommand: echo
arguments:
- $(inputs.one)

inputs:
  one:
    type: boolean?
    default: false
    inputBinding:
      prefix: one

outputs: []
```

Results in:

```
WARNING:toil.leader:R/c/jobZHPuTS    Traceback (most recent call last):
WARNING:toil.leader:R/c/jobZHPuTS      File "/Users/johnsoni/.virtualenvs/pipeline_test/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript
WARNING:toil.leader:R/c/jobZHPuTS        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:R/c/jobZHPuTS      File "/Users/johnsoni/.virtualenvs/pipeline_test/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
WARNING:toil.leader:R/c/jobZHPuTS        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:R/c/jobZHPuTS      File "/Users/johnsoni/.virtualenvs/pipeline_test/lib/python2.7/site-packages/toil/job.py", line 1296, in _run
WARNING:toil.leader:R/c/jobZHPuTS        return self.run(fileStore)
WARNING:toil.leader:R/c/jobZHPuTS      File "/Users/johnsoni/.virtualenvs/pipeline_test/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 878, in run
WARNING:toil.leader:R/c/jobZHPuTS        jobobj[key][0]] is None:
WARNING:toil.leader:R/c/jobZHPuTS    KeyError: u'one'
```

My best guess is that it is somehow related to this change:

https://github.com/DataBiosphere/toil/commit/ceda59b5e6eedf7d92650e71ea74e99efa3a0e7e#diff-ee480085fcce06066f78f98d1188e663L751

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-55)
┆friendlyId: TOIL-55

**Comment by adamnovak** [comment] 2023-11-21 18:13
I think this might be a duplicate of #2727, and @mr-c gave the impression that the conformance tests test this now, so it must work. Probably.

**Closed by adamnovak** 2023-11-21 18:13 UTC
Labels: cwl, roadmap
