### ISSUE TITLE
Import/export job store tests sporadically fail against Azure

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#787] opened 2016-04-13 20:02 UTC
Jake, can you take a look at this? It's totally possible that there is nothing we can do about downtimes or unreliability on the Azure side. I just want you to look at the stack traces and think about if there is something we can do about them,

http://jenkins.cgcloud.info/job/toil-pull-requests/1081/

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-331)
┆Issue Number: TOIL-331

**Comment by cket** [comment] 2016-04-30 00:04
Another case, caused by AzureMissingResourceHttpError: 
http://jenkins.cgcloud.info/job/toil-pull-requests/1191/

**Comment by arkal** [comment] 2016-04-30 20:20
Another AzureMissingResourceError

http://jenkins.cgcloud.info/job/toil-pull-requests/1210/testReport/src.toil.test.src.jobCacheTest/AzureJobStoreCacheTest/testCacheEviction/

**Comment by arkal** [comment] 2016-05-02 21:55
FYI, my issue was resolved by not using the same jobstore name for the tests even though the jobstore is cleaned after every test.

**Closed** 2020-04-06 01:31 UTC
Labels: azure, bug, importexport
