### ISSUE TITLE
Separate AWS functions into lib.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3808] opened 2021-09-26 19:41 UTC
This is to help abstract out some of what was being done in: #3569

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1036)
┆friendlyId: TOIL-1036

**Comment by adamnovak** [comment] 2024-02-06 18:36
I'm going to close this as a duplicate of #4088.

**Closed by adamnovak** 2024-02-06 18:36 UTC
