### ISSUE TITLE
Flatcar fetch is still flaky?

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#4852] opened 2024-03-27 18:41 UTC
https://ucsc-ci.com/databiosphere/toil/-/jobs/63792

```
=================================== FAILURES ===================================
__________________________ AMITest.test_fetch_flatcar __________________________
[gw2] linux -- Python 3.10.13 /builds/databiosphere/toil/venv/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/builds/databiosphere/toil/src/toil/test/lib/test_ec2.py", line 83, in test_fetch_flatcar
    ami = aws_marketplace_flatcar_ami_search(self.ec2_client)
  File "/builds/databiosphere/toil/src/toil/lib/retry.py", line 292, in call
    return func(*args, **kwargs)
  File "/builds/databiosphere/toil/src/toil/lib/aws/ami.py", line 184, in aws_marketplace_flatcar_ami_search
    response: dict = ec2_client.describe_images(Owners=['aws-marketplace'],  # type: ignore
  File "/builds/databiosphere/toil/venv/lib/python3.10/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/builds/databiosphere/toil/venv/lib/python3.10/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeImages operation: AWS was not able to validate the provided access credentials
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1529)
┆Issue Number: TOIL-1529

**Comment by adamnovak** [comment] 2024-10-04 17:07
This is a duplicate of https://github.com/DataBiosphere/toil/issues/4475.

**Closed by adamnovak** 2024-10-04 17:07 UTC
