### ISSUE TITLE
Resubmission of entire job queue after successful completion

### ISSUE THREAD

**Issue by ntchuang** [DataBiosphere/toil#2730] opened 2019-07-05 18:43 UTC
My group has been trying to scale up our genomics analysis on AWS using Toil. We have performed testing on small sets of 10, 30, and 100 with a goal of 1000s of genomes. We have noticed an error that as far as we can tell cannot be consistently reproduced. For example, I submitted a 500 job run, and after Toil confirmed 500 jobs finished successfully, Toil/Mesos submits the 500 jobs again. There are no related error or warning messages before this occurs (there were 5 file transfer failures that retried successfully). I am using Toil 3.19 with all the extras. Any ideas why this is happening or how to debug this?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-391)
┆Issue Number: TOIL-391

**Comment by ionox0** [comment] 2019-07-07 17:59
Toil will submit all jobs twice, the second time it will not run the tool again but simply perform some sort of cleanup operation. Perhaps someone else could follow up but this may be an expected behavior

**Comment by ntchuang** [comment] 2019-07-08 13:45
I am still learning all this, but from scrutinizing the log files from previously working runs and another run with the same problem there are no messages to suggest why the leader node would resubmit the jobs to run again. Since we were testing on 10-30 samples we allowed it to resubmit, but with 500 samples and a larger cluster cost we can't allow this to occur.  

The only difference in log files from a run with resubmission and a normal run that I can see is after all the jobs are reported as successfully completed by the toil leader and they both update the jobStore bucket, the "resubmission" run will issue the entire job list again-whereas a normal run states "Finished toil run successfully".

**Comment by ionox0** [comment] 2019-07-08 21:07
hmm I'm not 100% sure, are there more outputs at the end of the run that submits the jobs multiple times? and do the resubmissions take the same amount of time to run as the original jobs? perhaps you could include a link to the log file?

**Comment by ntchuang** [comment] 2019-07-08 21:15
Here is the log file for the run in question. It is a 500 sample run.

[run.err.txt](https://github.com/DataBiosphere/toil/files/3370257/run.err.txt)

It also seems like the worker nodes were being "removed" and there were many errors occurring after resubmission. I destroyed the cluster after 6 worker nodes were removed.

**Comment by ntchuang** [comment] 2019-07-08 21:18
I was also looking through some of the other issues listed, and I saw that there are some "unretryable" errors during s3 upload? Is it possible that after the 500 samples were completed there was an error uploading all the output files, and thus triggering resubmission of everything?

**Comment by adamnovak** [comment] 2019-07-11 23:35
@ntchuang In that log file, I see a few jobs that failed during downloads from S3 with read timeouts, and then near the end a bunch of jobs died because the Mesos agents they were running on went away (with `REASON_AGENT_REMOVED`). I don't know where the Mesos machines went either; you weren't running on the AWS spot market, right?

I don't see any upload errors, and at any rate upload errors ought to just cause the job that has them (and possibly other chained jobs on the same node, if using asynchronous uploads and caching) to fail. It shouldn't result in the whole workflow rerunning.

@ntchuang How do you know the whole workflow is rerunning? What lines in the log indicate this to you?

I do see multiple copies of this:

```
DEBUG:toil.jobStores.aws.jobStore:Instantiating <class 'toil.jobStores.aws.jobStore.AWSJobStore'> for region us-east-1 and name prefix 'nctj1'
```

I thought that only one jobStore instance would be used for the whole run, but here we see it creating several. Is that the basis for deciding that the workflow is running multiple times? If it is, it must be some loop around the jobStore construction, which should be fairly easy to find...

**Comment by ntchuang** [comment] 2019-07-12 00:39
@adamnovak this issue has occurred only a few times in the past so I recognized it. I knew the jobs were resubmitted after it was completed because after the 500 jobs reported `ended successfully` 505 times (5 for the failed downloads that retried) the `INFO:toil.leader: Issued job` message can be seen 500 times again (starting at line 7774, sorry I didn't realize this logfile would print the download status on individual lines). When I destroyed the cluster after 6 jobs completed a second time, I checked the output bucket and it contained all the expected files for 500 jobs. 

I am not using spot instances. 

When I compared this logfile to our successful runs, I've always noticed that the jobStore is "Instantiated" at the start of the workflow before the job is submitted, when jobs are completed, and twice more before the workflow is completed. It is the same here I believe, except instead of 
```
932 INFO:toil.leader:Finished toil run successfully.
933 INFO:toil.common:Successfully deleted the job store: <toil.jobStores.aws.jobStore.AWSJobStore object at 0x7f3b585cbf10>
```
it resubmits the 500. I have attached a normal run for comparison.

[run.err2.txt](https://github.com/DataBiosphere/toil/files/3384461/run.err2.txt)

@adamnovak do you believe the multiple instantiations of jobStore is an errant behavior? Could this cause an issue with Amazon SimpleDB to cause resubmission of all the jobs?

**Comment by adamnovak** [comment] 2019-07-12 18:38
Multiple instantiations of the job store is apparently expected behavior.

At least one instance is coming from [here](https://github.com/DataBiosphere/toil/blob/9b15b1da5f50a0638899423459c5194e1a507970/src/toil/job.py#L1806-L1827) in the Promise class; when we [unpickle the root job's return value](https://github.com/DataBiosphere/toil/blob/d6fb93491de53b24a3b05cc2849796663e1b61a3/src/toil/leader.py#L248) at the end of the leader's main loop, we unpickle a Promise, which, being the first time we deal with a Promise in the leader process, means we have to open up the job store again.

How sure are you of the normal-ness of your normal run, though? Looking at your log, it looks like it issues 70 jobs, but some of the jobs re-use job batch system ID numbers, which AFAIK should never happen. It does one set of jobs 2-31, and then starts re-using numbers. If there's cross-talk between different jobs, we could convince ourselves that the root job (and successors) needs to be retried because some other job failed, causing the restarts visible in the problem runs. There are some warnings in the logs that support this notion of cross-talk:

```
WARNING:toil.leader:A result seems to already have been processed for job 0
WARNING:toil.batchSystems.mesos.batchSystem:Job 9 returned exit code 0 but isn't tracked as running.
WARNING:toil.batchSystems.mesos.batchSystem:Job 9 returned exit code 0 from unknown host.
WARNING:toil.leader:A result seems to already have been processed for job 9
WARNING:toil.batchSystems.mesos.batchSystem:Job 6 returned exit code 0 but isn't tracked as running.
WARNING:toil.batchSystems.mesos.batchSystem:Job 6 returned exit code 0 from unknown host.
WARNING:toil.leader:A result seems to already have been processed for job 6
WARNING:toil.batchSystems.mesos.batchSystem:Job 17 returned exit code 0 but isn't tracked as running.
WARNING:toil.batchSystems.mesos.batchSystem:Job 17 returned exit code 0 from unknown host.
WARNING:toil.leader:A result seems to already have been processed for job 17
WARNING:toil.batchSystems.mesos.batchSystem:Job 7 returned exit code 0 but isn't tracked as running.
WARNING:toil.batchSystems.mesos.batchSystem:Job 7 returned exit code 0 from unknown host.
WARNING:toil.leader:A result seems to already have been processed for job 7
WARNING:toil.batchSystems.mesos.batchSystem:Job 2 returned exit code 0 but isn't tracked as running.
WARNING:toil.batchSystems.mesos.batchSystem:Job 2 returned exit code 0 from unknown host.
WARNING:toil.leader:A result seems to already have been processed for job 2
WARNING:toil.batchSystems.mesos.batchSystem:Job 20 returned exit code 0 but isn't tracked as running.
WARNING:toil.batchSystems.mesos.batchSystem:Job 20 returned exit code 0 from unknown host.
WARNING:toil.leader:A result seems to already have been processed for job 20
WARNING:toil.batchSystems.mesos.batchSystem:Job 21 returned exit code 0 but isn't tracked as running.
WARNING:toil.batchSystems.mesos.batchSystem:Job 21 returned exit code 0 from unknown host.
WARNING:toil.leader:A result seems to already have been processed for job 21
```

However, the code it uses to produce these job IDs looks fine: it is getting them from the embedded single machine batch system that handles the local jobs, so that the Mesos jobs and the local coordination jobs don't collide in the ID space:

https://github.com/DataBiosphere/toil/blob/9b15b1da5f50a0638899423459c5194e1a507970/src/toil/batchSystems/abstractBatchSystem.py#L372-L380

It looks almost as if something is resetting that counter somehow...

This would be a lot easier to dig into if your log had the debug messages from the leader and the Mesos scheduler, so I could see what it thought it was doing. However, I'm only seeing debug messages from Boto. Did you run these runs with `--logDebug`?

Also, are you running multiple simultaneous Toil runs against the same Mesos? I've heard that that can go wrong.

**Comment by ntchuang** [comment] 2019-07-12 19:20
We are currently attempting to reproduce this issue, but we can try to run our next jobs with `--logDebug`. 

Just to answer some of your questions, the "normal" run was a 30 sample test that actually finishes the entire workflow of 4 steps/toil runs. The step with the said issue is the first step, which is completed by line 949 in the normal run log file. Sorry for the confusion.

Lastly, we are running the toil runs sequentially against the same Mesos as the subsequent steps require input files from the previous steps.

**Comment by adamnovak** [comment] 2019-07-12 20:07
It should be fine to run sequentially against the same Mesos, I think.

If you can reproduce any of those warning messages about jobs
returning without being issued or having already produced results, I
would be interested in the --logDebug logs for them. I suspect that's
the underlying issue and it only sometimes manifests as redoing the
whole workflow.

**Comment by ntchuang** [comment] 2019-07-12 20:39
When you say use `--logDebug`, you meant during `toil launch-cluster` or was it for `toil-cwl-runner`? I guess I can enable it for both.

**Comment by adamnovak** [comment] 2019-07-12 21:21
Just during the actual workflow (toil-cwl-runner).

**Comment by ntchuang** [comment] 2019-07-26 18:31
@adamnovak So we encountered the resubmission error last week when we submitted 500 samples. Looks like at line 3216737 it has finished the 500 samples. At line 3217061it is resubmitting step1b for the 500 samples again. I think there must be an error updating the jobStore as I see this message twice: `DEBUG:toil.leader:Job: 53751991-4ef3-46c5-bb7e-8bceec430af8 has 500 successors to schedule`?
 
[run.err.gz](https://github.com/DataBiosphere/toil/files/3436942/run.err.gz)

**Comment by jeffrey856** [comment] 2020-02-19 22:09
Hello @ntchuang

What is your status currently? Is this problem still persistent with the new updates to toil? If so, can you please provide the python and toil versions, the CWL files, and the specific CLI commands you are running?

**Comment by ntchuang** [comment] 2020-02-20 14:33
I stopped trying to debug this issue. It's been many months since I have tried working on this since I hadn't heard back from Adam. The software engineer who I was working with couldn't reproduce the error, and the only difference was he was using an older version of toil. We will probably restart efforts on turning our tool into production in a few months.

**Comment by jeffrey856** [comment] 2020-02-22 00:10
If that's the case I will close this issue! Feel free to re-open this issue if this ever pops up again!

**Closed by jeffrey856** 2020-02-22 00:10 UTC
