### ISSUE TITLE
Magic deployment of a virtualenv from your machine to autoscaling cluster

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2697] opened 2019-05-24 15:55 UTC
You shouldn't need to log in to the Toil cluster head node at all.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-374)
┆Issue Number: TOIL-374

**Comment by DailyDreaming** [comment] 2020-04-16 00:39
Looks like a duplicate of #2631.

**Closed by DailyDreaming** 2020-04-16 00:39 UTC
