### ISSUE TITLE
Tool can't authenticate to Docker registry

### ISSUE THREAD

**Issue by brucehoff** [DataBiosphere/toil#2166] opened 2018-04-03 20:54 UTC
I understand that a cwl tool descriptor can tell Toil to run code in a Docker container.  However, we have a case in which the `docker run` command has custom parameters, so we wish to invoke `docker run` directly.  Before running a container the repository must be pulled from a registry (unless it's already resident on the worker node.)  We have found that the worker node is unable to pull the specified image from the Docker registry *if the image is private*.  That is, the worker seems unable to use the Docker registry credentials cached locally.  To reproduce the issue:

### First, the happy case that works:
docker_run_tool.cwl:
```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool
baseCommand: docker
arguments: [run, --rm, -i, $(inputs.docker_repository)]

stdout: stdout.txt

inputs:
 docker_repository:
  type: string

outputs:
 stdout:
  type: stdout
```
docker_run_job_hello_world.cwl:
```
docker_repository: hello-world
```
(`hello-world` is a public Docker repository hosted on DockerHub.)

```
toil-cwl-runner --retryCount 0 docker_run_tool.cwl docker_run_job_hello_world.cwl 
...
SAGE-C02H51GMDV17.local 2018-04-03 13:45:22,980 MainThread INFO toil.leader: Finished toil run successfully
2018-04-03 13:45:22,980 - toil.leader - INFO - Finished toil run successfully
{
    "stdout": {
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709", 
        "basename": "stdout.txt", 
        "nameext": ".txt", 
        "nameroot": "stdout", 
        "http://commonwl.org/cwltool#generation": 0, 
        "location": "file:///Users/bhoff/Documents/toil/stdout.txt", 
        "class": "File", 
        "size": 0
    }
SAGE-C02H51GMDV17.local 2018-04-03 13:45:23,133 MainThread INFO toil.common: Successfully deleted the job store: <toil.jobStores.fileJobStore.FileJobStore object at 0x10a109c50>
}2018-04-03 13:45:23,133 - toil.common - INFO - Successfully deleted the job store: <toil.jobStores.fileJobStore.FileJobStore object at 0x10a109c50>
```

### Now, replace the repository with a private one:

docker_run_job_private_repository.cwl:
```
docker_repository: docker.synapse.org/syn4224222/dm-python-example
```

This is a private Docker repository in docker.synapse.org.  The credentials are cached on the worker node.

```
toil-cwl-runner --retryCount 0 docker_run_tool.cwl docker_run_job_private_repository.cwl 
...
INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.15.0-0e3a87e738f5e0e7cff64bfdad337d592bd92704.
[job docker_run_tool.cwl] /Users/bhoff/Documents/toil/out_tmpdirreniBQ$ docker \
    run \
    --rm \
    -i \
    docker.synapse.org/syn4224222/dm-python-example > /Users/bhoff/Documents/toil/out_tmpdirreniBQ/stdout.txt
INFO:cwltool:[job docker_run_tool.cwl] /Users/bhoff/Documents/toil/out_tmpdirreniBQ$ docker \
    run \
    --rm \
    -i \
    docker.synapse.org/syn4224222/dm-python-example > /Users/bhoff/Documents/toil/out_tmpdirreniBQ/stdout.txt
Unable to find image 'docker.synapse.org/syn4224222/dm-python-example:latest' locally
docker: Error response from daemon: pull access denied for docker.synapse.org/syn4224222/dm-python-example, repository does not exist or may require 'docker login'.
See 'docker run --help'.
[job docker_run_tool.cwl] completed permanentFail
WARNING:cwltool:[job docker_run_tool.cwl] completed permanentFail
...
```

Now let's verify that we can, in fact, pull the repository:
```
[~]  docker pull docker.synapse.org/syn4224222/dm-python-example
Using default tag: latest
latest: Pulling from syn4224222/dm-python-example
21f90b3df721: Already exists 
4e14c1a5f55c: Already exists 
9f4cbf65c5bf: Already exists 
26be4f9eea83: Already exists 
120ae6580aff: Already exists 
f0a73deb6053: Already exists 
b19b4481b908: Already exists 
3295f82b0f66: Already exists 
f5ad1b9c2305: Already exists 
865dfbedd5e0: Already exists 
c33f47d79e39: Already exists 
9a7a653c2c5f: Pull complete 
0f6bd60adb54: Pull complete 
14de1157f81e: Pull complete 
ea9eca5479fb: Pull complete 
9d70200db821: Pull complete 
2bed54cc7096: Pull complete 
Digest: sha256:658adcba7e48fb6338cfb15d8b4cbd7ad882534db47164430448a63a44461812
Status: Downloaded newer image for docker.synapse.org/syn4224222/dm-python-example:latest
```

With the repository now on the machine we can run the workflow:

```
toil-cwl-runner --retryCount 0 docker_run_tool.cwl docker_run_job_private_repository.cwl 
...
SAGE-C02H51GMDV17.local 2018-04-03 13:51:56,608 MainThread INFO toil.leader: Finished toil run successfully
2018-04-03 13:51:56,608 - toil.leader - INFO - Finished toil run successfully
{
    "stdout": {
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709", 
        "basename": "stdout.txt", 
        "nameext": ".txt", 
        "nameroot": "stdout", 
        "http://commonwl.org/cwltool#generation": 0, 
        "location": "file:///Users/bhoff/Documents/toil/stdout.txt", 
        "class": "File", 
        "size": 0
    }
SAGE-C02H51GMDV17.local 2018-04-03 13:51:56,738 MainThread INFO toil.common: Successfully deleted the job store: <toil.jobStores.fileJobStore.FileJobStore object at 0x10908cc10>
}2018-04-03 13:51:56,738 - toil.common - INFO - Successfully deleted the job store: <toil.jobStores.fileJobStore.FileJobStore object at 0x10908cc10>

```

So the problem seems to be that when running `docker run` Toil doesn't provide access to the cached registry credentials.  Docker's convention is that the credentials are found in `~/.docker/config.json` and other experiments show that Toil changes the `HOME` environment variable from `~` to the temp dir used for the workflow.  Our guess is that this is the reason that Docker can't authenticate.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-245)
┆Issue Number: TOIL-245

**Comment by mr-c** [comment] 2018-04-04 12:05
FYI, interacting with stateful services and wrapping the Docker runtime itself in CWL are not supported use cases for CWL (which has reproducible research workflows at its core). You are likely to have a better experience using other automation technologies to manage your infrastructure :-)

**Comment by brucehoff** [comment] 2018-04-04 14:05
We found a solution (workaround?):  Toil/CWLTool allows the creation of a file as part of running a tool. (See http://www.commonwl.org/user_guide/14-runtime/) I added this to the tool definition:

```
requirements:
  InitialWorkDirRequirement:
    listing:
      - entryname: .docker/config.json
        entry: |
          {"auths": {"$(inputs.docker_registry)": {"auth": "$(inputs.docker_registry_auth)"}}}

inputs:
 docker_registry:
  type: string
 docker_registry_auth:
  type: string
```

The registry address and credentials are passed in at run time.  I verified that this works!  Two downsides are:
- Leaves a copy of the credentials in the job's temp folder afterwards, which does not seem secure.
- Seems like the credentials need to go into the job definition file whereas it would be preferable to pass them on the command line.  (Toil seems to allow job param's to go on the command line or in a file but not *both*.)

**Comment by brucehoff** [comment] 2018-04-04 14:12
Regarding @mr-c comments:

> interacting with stateful services ... are not supported 

Not sure what the 'state' is here that you are referring to.

> wrapping the Docker runtime itself in CWL are not supported 

That doesn't seem right, see http://www.commonwl.org/user_guide/07-containers/

If you are saying that calling `docker run` directly rather than using `DockerRequirement` is not supported, then I can accept that.  If so, there is another issue which is that, as far as I can tell, Toil/CWLTool does not allow additional parameters to be added to `docker run`, beyond its own.

**Comment by mr-c** [comment] 2018-04-05 09:57
Firstly, as an individual and as a project we are happy for people to use the CWL standards in any way they find useful. However I do like to set expectations for what CWL was designed to do and not to do.

> > interacting with stateful services ... are not supported

> Not sure what the 'state' is here that you are referring to.

It looks like you are wanting to configure and control the Docker daemon from within CWL. The Docker daemon maintains [state](https://en.wikipedia.org/wiki/State_(computer_science))/information about what docker containers and images are available, their versions, etc..

> > wrapping the Docker runtime itself in CWL are not supported

> That doesn't seem right

The CWL standards support the use of Docker software containers, but they do not specify which Docker-compatible engine is being used to run those containers. It could be Singularity, udocker, etc. You can't depend that the `docker` application is available for direct access; only `DockerRequirement` is available as a control interface. However, specific platforms or workflow runners (like `toil-cwl-runner`) could expose additional configuration options that are specific to them.

All that being said; if it works for you then that is fine :smile: but it won't be portable and it is unlikely to be prioritized from a support perspective by myself or others.

**Would it be enough if `toil-cwl-runner` had a method for exporting docker registry options to the nodes?** That seems like a reasonable thing to implement; ideally in a way that would also be useful to the other Docker engines that `toil-cwl-runner` supports like udocker and Singularity.

One work around you could is to set the `DOCKER_CONFIG` to a cluster wide accessible path prior to executing `toil-cwl-runner --preserve-environment DOCKER_CONFIG` followed the remainder of your regular options.

> The registry address and credentials are passed in at run time. […]Two downsides are:
Leaves a copy of the credentials in the job's temp folder afterwards, which does not seem secure.

Agreed, this is why for v1.1 we are adding a `secret` field to the input specification https://github.com/common-workflow-language/common-workflow-language/issues/652 so that platforms can do their best to guard them.

**Comment by brucehoff** [comment] 2018-04-06 01:15
> I do like to set expectations for what CWL was designed to do and not to do

OK, I am new to this technology and would like to understand it better.  Is it within the intended use of CWL to write a workflow which interacts with the Cloud (e.g., takes as input a URL and, during the workflow execution, retrieves the file to use as an input)?  Or is it expected that workflows operate only on resources which have been placed locally on worker nodes prior to starting the workflow?  

> they do not specify which Docker-compatible engine is being used to run those containers. It could be Singularity, udocker, etc. 

Your point is well taken. It would be cleaner to indicate that a docker container is to be run (and let the CWL runner start up and run the container) rather than to invoke `docker run` directly in the CWL script.  As mentioned above this means that for some real-world cases there need to be additional run options that can be passed in the CWL file.  Just to give an example:  If the containerized code leverages GPUs available on the host, the GPU devices need to be mounted (in the manner of other volumes) to the container.  As far as I have seen CWL does not provide a way to specify such volume mounts when invoking the `DockerRequirement`.  

> Would it be enough if toil-cwl-runner had a method for exporting docker registry options to the nodes?

Yes, but since the 'options' of interest are the user's registry login credentials, they would have to be passed securely and available only to the workflow for which they were intended.  This is basically the approach I used in the work-around I suggested yesterday but, as you point out, it's specific to the Docker client and might fail if some other Docker-compatible runtime (like Singularity) were used.

Thank you for the other suggestions given above.

**Comment by arostamianfar** [comment] 2019-02-04 21:07
@IanMcDowell did you find the answer to your question? I'm running into the same issue and was wondering how/if you solved it.

**Comment by IanMcDowell** [comment] 2019-02-06 18:50
@arostamianfar I didn't find a satisfactory answer, but I found a workaround.

My workaround was to log into ECR from the leader node using a more traditional approach, e.g.:
```
CACHED_CREDS=/root/.cache/aws/cached_temporary_credentials
AWS_ACCESS_KEY_ID=$(head -n1 $CACHED_CREDS)
AWS_SECRET_ACCESS_KEY=$(head -n2 $CACHED_CREDS | tail -n1)
AWS_SESSION_TOKEN=$(head -n3 $CACHED_CREDS | tail -n1)
echo "Exporting cached AWS credentials"
export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
echo "Logging into Docker so that ~/.docker/config.json is created"
eval $(/root/.local/bin/aws ecr get-login --no-include-email --region us-east-1)
```
Then I copied the generated credentials (`~/.docker/config.json`) from the leader node to the worker nodes using their public IP addresses. From a security standpoint, this approach seems questionable, but it does work.

**Comment by arostamianfar** [comment] 2019-02-07 00:23
@IanMcDowell Thanks for letting me know! I ended up doing another workaround by modifying the Toil appliance image to use [`amazon-ecr-credential-helper`](https://github.com/awslabs/amazon-ecr-credential-helper) (I ended up using an existing public docker image that had this binary in it). For reference, here's the Dockerfile:
```
FROM quay.io/ucsc_cgl/toil:latest
RUN sudo printf '#!/bin/sh\n%s\n%s\n' \
    'SECRET=$(docker run --rm -e METHOD=$1 -e REGISTRY=$(cat -) pottava/amazon-ecr-credential-helper)' \
    'echo $SECRET | grep Secret' > \
    /usr/local/bin/docker-credential-ecr-login && \
    sudo chmod +x /usr/local/bin/docker-credential-ecr-login && \
    sudo mkdir ~/.docker && \
    sudo echo '{ "credsStore": "ecr-login" }' > ~/.docker/config.json
```
I then set `TOIL_APPLIANCE_SELF` to point to this new image.
For some reason, I needed to do the same in the AMI as well (i.e. start from clean CoreOS and add these two files in it) and then override it using `TOIL_AWS_AMI`.
It's a bit more work initially, but it's secure and avoids doing any manual setup once the cluster is up. It also requires periodically updating the docker image whenever a new version of Toil is available, but it's the "best" workaround I found so far.

Overall, I think it would be great if Toil provided these out of the box as I think it's a common use case.

**Comment by arostamianfar** [comment] 2019-03-22 18:08
@IanMcDowell FYI, with #2561 merged, you can now run `export TOIL_CUSTOM_DOCKER_INIT_COMMAND='pip install awscli && eval $(aws ecr get-login --no-include-email --region us-east-1)'` in the leader node and it will authenticate all workers with ECR in a secure way without any manual interventions!
Note that the above command only works on EC2 instances as credentials are retrieved from instance metadata.

**Comment by adamnovak** [comment] 2019-05-16 21:03
I think between #2561 and the workaround mentioned, I am going to close this issue as fixed. If we want to change something else (like making Toil/CWL not move $HOME) I think that should be a new issue.

**Closed by adamnovak** 2019-05-16 21:03 UTC
