### ISSUE TITLE
WDL Beta

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2651] opened 2019-04-25 21:57 UTC
┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/TOIL-351)
┆Issue Number: TOIL-351

**Comment by DailyDreaming** [comment] 2020-04-15 23:17
Duplicate of #2170.

**Closed by DailyDreaming** 2020-04-15 23:17 UTC
