### ISSUE TITLE
How to figure out progress using --stats

### ISSUE THREAD

**Issue by gijzelaerr** [DataBiosphere/toil#2580] opened 2019-04-02 10:14 UTC
hi! I'm trying to parse the output of `--stats` to determine the progress of a pipeline. I'm not sure if this is possible with the current output? But I can try anyway :)

To test I have a simple workflow with a couple of steps that just sleep, each with a different time:

https://github.com/gijzelaerr/buis/blob/master/testdata/sleep_workflow.cwl

assuming this PR got merged:

https://github.com/DataBiosphere/toil/pull/2533

When I parse the stats folder I find the following data:

## worker
```
{'total_number': 3.0, 'total_time': 12.75978136062622, 'median_time': 1.829918384552002, 'average_time': 4.253260453542073, 'min_time': 0.14540910720825195, 'max_time': 10.784453868865967, 'total_clock': 1.7540779999999996, 'median_clock': 0.7849659999999998, 'average_clock': 0.5846926666666665, 'min_clock': 0.145289, 'max_clock': 0.8238229999999997, 'total_wait': 11.005703360626221, 'median_wait': 1.0060953845520022, 'average_wait': 3.668567786875407, 'min_wait': 0.00012010720825195165, 'max_wait': 9.999487868865966, 'total_memory': 280384.0, 'median_memory': 92536.0, 'average_memory': 93461.33333333333, 'min_memory': 92276.0, 'max_memory': 95572.0, 'name': 'worker'}
```

## jobs
```
{'total_number': 3.0, 'total_time': 12.367944955825806, 'median_time': 1.7048237323760986, 'average_time': 4.122648318608602, 'min_time': 0.021138668060302734, 'max_time': 10.641982555389404, 'total_clock': 1.3624609999999997, 'median_clock': 0.6425759999999998, 'average_clock': 0.45415366666666657, 'min_clock': 0.021091000000000026, 'max_clock': 0.6987939999999999, 'total_wait': 11.005483955825806, 'median_wait': 1.0060297323760987, 'average_wait': 3.6684946519419355, 'min_wait': 4.766806030270798e-05, 'max_wait': 9.999406555389404, 'total_memory': 280384.0, 'median_memory': 92536.0, 'average_memory': 93461.33333333333, 'min_memory': 92276.0, 'max_memory': 95572.0, 'name': 'jobs', 'median_number_per_worker': 3, 'average_number_per_worker': 3.0, 'min_number_per_worker': 3, 'max_number_per_worker': 3}
```

### CWLWorkflow
```
 {'total_number': 1.0, 'total_time': 0.021138668060302734, 'median_time': 0.021138668060302734, 'average_time': 0.021138668060302734, 'min_time': 0.021138668060302734, 'max_time': 0.021138668060302734, 'total_clock': 0.021091000000000026, 'median_clock': 0.021091000000000026, 'average_clock': 0.021091000000000026, 'min_clock': 0.021091000000000026, 'max_clock': 0.021091000000000026, 'total_wait': 4.766806030270798e-05, 'median_wait': 4.766806030270798e-05, 'average_wait': 4.766806030270798e-05, 'min_wait': 4.766806030270798e-05, 'max_wait': 4.766806030270798e-05, 'total_memory': 95572.0, 'median_memory': 95572.0, 'average_memory': 95572.0, 'min_memory': 95572.0, 'max_memory': 95572.0, 'name': 'CWLWorkflow'}
```

### 'file:///home/gijs/Work/buis/scratch/repo/15/testdata/sleep.cwl
```
{'total_number': 2.0, 'total_time': 12.346806287765503, 'median_time': 10.641982555389404, 'average_time': 6.1734031438827515, 'min_time': 1.7048237323760986, 'max_time': 10.641982555389404, 'total_clock': 1.3413699999999997, 'median_clock': 0.6987939999999999, 'average_clock': 0.6706849999999999, 'min_clock': 0.6425759999999998, 'max_clock': 0.6987939999999999, 'total_wait': 11.005436287765503, 'median_wait': 9.999406555389404, 'average_wait': 5.502718143882752, 'min_wait': 1.0060297323760987, 'max_wait': 9.999406555389404, 'total_memory': 184812.0, 'median_memory': 92536.0, 'average_memory': 92406.0, 'min_memory': 92276.0, 'max_memory': 92536.0, 'name': 'file:///home/gijs/Work/buis/scratch/repo/15/testdata/sleep.cwl'}
```

So what I can query is all kind of time metrics, but what isn't very obvious to me is figure out which steps have already been executed and which steps are still pending. I could precompute the execution graph in advance and then augment that data with info from these dics, but I don't think it contains all required information. Am I reading this wrongly or is such a thing not possible? Would it be hard to add such a feature?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-38)
┆friendlyId: TOIL-38

**Comment by adamnovak** [comment] 2019-04-02 17:12
Since Toil can create jobs dynamically, there's no way to know in
advance the total number of jobs that will need to be run in a
workflow, short of reasoning about the workflow code itself. In theory
you should be able to tell how many jobs have been completed, and how
many jobs exist but haven't completed yet, by looking at the jobstore
of a workflow that has stopped in the middle. But I believe that
--stats was designed for completed workflows, so it might not look at
not-yet-run jobs. And I suspect you won't be able to get a consistent
view of a workflow that is actively in progress, because the job store
is going to be being written to as you try to read it.

Did you get these stats from a completed workflow? Or a
partially-completed workflow? It looks to me like all the jobs have
completed because there's two runs' worth of stats for the sleeping
job, and then some stats for an orchestrating CWLWorkflow job.

**Comment by illusional** [comment] 2019-07-01 22:45
Hi, jumping into this too. Mainly concerned around CWL submissions, but also trying to track the progress. I've noticed you can let Toil do some of that work for you using `toil stats --raw JobStoreId`. I can't determine a super great way get the location job store, except by parsing the stdout.

What's the difference (and implications) of jobName and displayName? I can't find any documentation about them, but I know it's what the `--raw` output is keyed on.

Is there a way to inject extra metadata to appear on the JSON output of each job? I've been trying to modify the CWLToil file to include better names, but it would be great to inject things like a shard key or the parent workflow name. This output doesn't prepare encapsulated / child jobs / sub-workflows in a logical structure from what I can tell, but this may just be the way the CWLToil file prepares the jobs. I have a representation of how the graph is built that I can refer to when I poll for the stats, but just trying to avoid that.

I think, ideally I'd want something something call:
```json
{
    'jobName': [{
        start, finish, etc, 
        children: {
            'childJobName': [/*same nested object*/]
        },
        meta: { /* extra keys specified on object */ }
    }]

}
```

**Comment by adamnovak** [comment] 2019-07-01 23:49
I don't think your nesting system is going to work there; a job in Toil can be a child of 0 or more jobs, and/or a follow-on of zero or more jobs. So you can't just nest the stats neatly in a tree for anything that works on general Toil workflows as well as CWL ones.

I don't really have good answers for your other questions. Someone probably has to dig around the code to try and work out why we have both a name and a display name. It really should be documented, but isn't.

What do you mean by "exposing" the job ID from the batch system? Jobs already know and publiclly expose their own IDs, I think. The batch system can have its own internal IDs for jobs (i.e. a number in the HPC queue submission system), but those aren't necessarily unique or preserved across restarts or retries and shouldn't really be visible outside the batch system AFAIK, because everyone other than the batch system should be using the normal non-batch-system-scoped job ID.

**Comment by adamnovak** [comment] 2023-03-21 17:15
We've improved the Toil status commands a bit since this was opened. If you use `toil status --printStatus` it can tell you about currently running jobs in a way that might be useful for assessing workflow progress.

We also set up a "message bus" system which would be recommended as the integration point for monitoring a running workflow if you want to go beyond what's available on the CLI. You can grab the message bus path [like this](https://github.com/DataBiosphere/toil/blob/dc7d7da1e5279c6aa27c19c16da86730b294f8ad/src/toil/utils/toilStatus.py#L38-L47) and then reconstruct the states of the jobs [like this](https://github.com/DataBiosphere/toil/blob/dc7d7da1e5279c6aa27c19c16da86730b294f8ad/src/toil/utils/toilStatus.py#L236)

I am going to close this issue.

**Closed by adamnovak** 2023-03-21 17:15 UTC
Labels: roadmap

**Comment by adamnovak** [comment] 2023-03-21 17:18
For CWL workflows, there isn't a great way to get the job store location if you let `toil-cwl-runner` invent one for you. If you use the `--jobStore` option, you can supply a location where the job store should be placed, which you can then use with the other Toil utilities to interact with the workflow.
