### ISSUE TITLE
Toil crashes on job that writes many files to S3 store.

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#2706] opened 2019-06-06 13:32 UTC
I have a Toil job that downloads a few big files, splits them up into thousands and thousands of little files, and uploads them back to the job store with  `job.fileStore.writeGlobalFile()`.

One one particular large input, this job crashes repeatedly.  It's able to download and split the files, but then this always happens. (I tried wrapping up my call to `writeGlobalFile` to repeat on failure with no success).  Is there a jobstore size limit or something that I can be hitting?    

```
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/venv/local/lib/python2.7/site-packages', name='toil_vg.vg_call', fromVirtualEnv=True).
 DEBUG:toil.jobStores.aws.jobStore:Updating job d4aca0e5-6853-4001-aa1f-f14021f3d61b
 Exception in thread Thread-2685:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
     self.run()
   File "/usr/local/lib/python2.7/dist-packages/toil/lib/threading.py", line 73, in run
     self.tryRun( )
   File "/usr/local/lib/python2.7/dist-packages/toil/lib/threading.py", line 79, in tryRun
     super( ExceptionalThread, self ).run( )
   File "/usr/lib/python2.7/threading.py", line 754, in run
     self.__target(*self.__args, **self.__kwargs)
   File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/utils.py", line 90, in _reader
     self.readFrom(readable)
   File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 1069, in readFrom
     info.version = upload.complete_upload().version_id
   File "/usr/local/lib/python2.7/dist-packages/boto/s3/multipart.py", line 319, in complete_upload
     self.id, xml)
   File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 1806, in complete_multipart_upload
     response.status, response.reason, body)
 S3ResponseError: S3ResponseError: 200 OK
 <?xml version="1.0" encoding="UTF-8"?>
 <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>CE5677975BB1F389</RequestId><HostId>Sh+0QWWXseH2V9jmZfuNBMJMq5B4aOGF+H6AX2dNolSSpszQYeqGOEO6MuBfZuOXcVwuZwlcR10=</HostId></Error>
 
 DEBUG:toil.fileStore:LOG-TO-MASTER: Job fdb0b793-389c-422b-a24d-2a9e1fe6d1be used 0.00% (8.0 KB [8192B] used, 1.0 GB [1073741824B] requested) at the end of its run.
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 331, in workerScript
     job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
   File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1380, in _runner
     self._serialiseExistingJob(jobGraph, jobStore, returnValues)
   File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1302, in _serialiseExistingJob
     self._serialiseJobGraph(jobGraph, jobStore, returnValues, False)
   File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1271, in _serialiseJobGraph
     job._serialiseJob(jobStore, jobsToJobGraphs, jobGraph)
   File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1151, in _serialiseJob
     pickle.dump(self, fileHandle, pickle.HIGHEST_PROTOCOL)
   File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
     self.gen.next()
   File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 528, in writeFileStream
     yield writable, info.fileID
   File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
     self.gen.next()
   File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 1087, in uploadStream
     yield writable
   File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/utils.py", line 112, in __exit__
     self.thread.join()
   File "/usr/local/lib/python2.7/dist-packages/toil/lib/threading.py", line 86, in join
     raise_(type, value, traceback)
   File "/usr/local/lib/python2.7/dist-packages/toil/lib/threading.py", line 73, in run
     self.tryRun( )
   File "/usr/local/lib/python2.7/dist-packages/toil/lib/threading.py", line 79, in tryRun
     super( ExceptionalThread, self ).run( )
   File "/usr/lib/python2.7/threading.py", line 754, in run
     self.__target(*self.__args, **self.__kwargs)
   File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/utils.py", line 90, in _reader
     self.readFrom(readable)
   File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 1069, in readFrom
     info.version = upload.complete_upload().version_id
   File "/usr/local/lib/python2.7/dist-packages/boto/s3/multipart.py", line 319, in complete_upload
     self.id, xml)
   File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 1806, in complete_multipart_upload
     response.status, response.reason, body)
 S3ResponseError: S3ResponseError: 200 OK
 <?xml version="1.0" encoding="UTF-8"?>
 <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>CE5677975BB1F389</RequestId><HostId>Sh+0QWWXseH2V9jmZfuNBMJMq5B4aOGF+H6AX2dNolSSpszQYeqGOEO6MuBfZuOXcVwuZwlcR10=</HostId></Error>
 ERROR:toil.worker:Exiting the worker because of a failed job on host ip-172-31-26-53.us-west-2.compute.internal
 DEBUG:toil.jobStores.aws.jobStore:Loaded job 9be3cf22-f68d-4c83-98d9-77a4938b7cbb
 WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'run_chunked_calling' 9be3cf22-f68d-4c83-98d9-77a4938b7cbb with ID 9be3cf22-f68d-4c83-98d9-77a4938b7cbb to 0
Added job: 'run_chunked_calling' 9be3cf22-f68d-4c83-98d9-77a4938b7cbb to active jobs
Built the jobs list, currently have 1 jobs to update and 0 jobs issued
Updating status of job 'run_chunked_calling' 9be3cf22-f68d-4c83-98d9-77a4938b7cbb with ID 9be3cf22-f68d-4c83-98d9-77a4938b7cbb: with result status: 0
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-379)
┆Issue Number: TOIL-379

**Comment by adamnovak** [comment] 2019-06-06 17:23
This doesn't look like it's really Toil's fault. AWS is throwing up internal errors.

This actually looks like it is having trouble not with the file uploads themselves, but with serializing a job. When you create those thousands of files, are you by chance turning around and passing a giant list of them as an argument or a job return value? In theory that ought to work, but maybe not doing that would work around the problem.

An underlying design issue here is that we can feed a stream of data to S3, and then at the end S3 can tell us that actually it dropped all our data on the floor, but at that point we may no longer have the data around, because S3 acknowledged receipt of each chunk we sent it, and we're getting our data from a stream. We wrap the [complete_upload() call in a retry loop](https://github.com/DataBiosphere/toil/blob/314229d0cee70fc828faa4bc89f05c43a5b0ecd2/src/toil/jobStores/aws/jobStore.py#L1067-L1069), but this error is not in the [list of retryable errors](https://github.com/DataBiosphere/toil/blob/314229d0cee70fc828faa4bc89f05c43a5b0ecd2/src/toil/jobStores/aws/utils.py#L375-L383), and it's possible that the whole upload needs to be retried.

If this is a reproducible failure, I doubt that just retrying the complete will work. But maybe it would help.

**Comment by glennhickey** [comment] 2019-06-06 17:54
It's happening when splitting a whole-genome graph/gam into chunks for
calling here.  It does return a list of dictionaries, one for each chunk:

https://github.com/vgteam/toil-vg/blob/master/src/toil_vg/vg_call.py#L620-L656

which get passed to the follow-on.  But we're only talking about 1200 items
in the list (splitting genome in 2.5mb chunks).  This doesn't seem like it
should be an unreasonable demand from Toil.

**Comment by adamnovak** [comment] 2022-12-14 22:45
I'm going to close this on the theory that this was AWS's bug. We've refactored the multipart upload code since then, but I'm still not sure if if we get a 200 OK code and an error body we will retry. But they really shouldn't send that.

If we see this again we can reopen this and actually add 200 to the list of retriable response codes.

**Closed by adamnovak** 2022-12-14 22:45 UTC
Labels: roadmap
