### ISSUE TITLE
"Name" tag on leader instance not being set (possibly similar to #2574)

### ISSUE THREAD

**Issue by brantfaircloth** [DataBiosphere/toil#2828] opened 2019-10-29 18:05 UTC
Good afternoon,

I ran into a problem where it does not appear the leader instance created by:
```
toil launch-cluster -z us-east-1a --keyPairName id_aws --leaderNodeType t2.medium faircloth-test
```
gets tagged correctly.  This creates a condition where a subsequent run of Cactus fails because of an empty value for `instance.tags["Name"]` in https://github.com/DataBiosphere/toil/blob/d2a76d3309150c7f6415cca2cec402c72755ea4c/src/toil/provisioners/aws/awsProvisioner.py#L126
A temporary workaround for the issue is simply to create a tag for the leader instance using the EC2 interface - then all works as it should, although this is not the expected behavior.

I'm using toil 3.20.0 on linux to start the cluster.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-441)
┆Issue Number: TOIL-441

**Comment by brantfaircloth** [comment] 2020-02-12 19:15
To follow up, I think this occurs because of improper placement of the positional argument `<cluster-name>` relative to the cluster optional args.  E.g. the tags do not seem to propagate when using:

`toil launch-cluster -z us-east-1a <cluster-name> --keyPairName id_aws --leaderNodeType t2.medium`

but they do appear to work as expected when using:

`toil launch-cluster -z us-east-1a --keyPairName id_aws --leaderNodeType t2.medium <cluster-name>`

**Comment by adamnovak** [comment] 2020-02-12 21:01
This is affecting me too, I think. It also prevents the instances from being torn down by `destroy-cluster`.

**Comment by adamnovak** [comment] 2020-02-12 23:22
Actually, it could just be that I typo'd the cluster name in my `toil destroy-cluster` command. But I can replicate the Name tag not being assigned, depending on where the name argument lands on the command line.

**Comment by jeffrey856** [comment] 2020-10-21 18:21
I am currently running through test scenario with the following commands:

- toil launch-cluster -z us-west-2a test-instance --keyPairName jwu157 --leaderNodeType t2.medium 
- toil launch-cluster test-instance -z us-west-2a --keyPairName jwu157 --leaderNodeType t2.medium 
- toil launch-cluster -z us-west-2a --keyPairName jwu157 --leaderNodeType t2.medium faircloth-test
Plus more variations of this command....

I am currently running **4.3.0a1-08e9d1476a79c53d4c8a52f77d3e39934b0ba0fc-py3.8** and can't seem to reproduce the bug. It seems to be fixed. I will be running more tests to check if the tags intermittently doesn't get added. Closing this ticket for the time being.


![Screen Shot 2020-10-21 at 11 06 39](https://user-images.githubusercontent.com/42762562/96765844-17792b00-138f-11eb-97d8-baf58cb324d9.png)

**Closed by jeffrey856** 2020-10-21 18:21 UTC
Labels: roadmap
