### ISSUE TITLE
thread.error: can't start new thread on UnivaGridEngine

### ISSUE THREAD

**Issue by 6br** [DataBiosphere/toil#2308] opened 2018-07-17 09:44 UTC
Toil failed when running on UnivaGridEngine cluster environment.

## Environments

Red Hat Enterprise Linux release 6.9 (Santiago)

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    1
Core(s) per socket:    12
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
```

## Error details

When I run the [quick start](http://toil.readthedocs.io/en/3.15.0/gettingStarted/quickStart.html) on the official document with `python helloWorld.py bucket`, it returned an error.

```
Traceback (most recent call last):
  File "sort.py", line 242, in <module>
    main()
  File "sort.py", line 236, in main
    memory=sortMemory))
  File "/home/6br/anaconda3/envs/toil/lib/python2.7/site-packages/toil/common.py", line 762, in start
    self._batchSystem = self.createBatchSystem(self.config)
  File "/home/6br/anaconda3/envs/toil/lib/python2.7/site-packages/toil/common.py", line 911, in createBatchSystem
    return batchSystemClass(**kwargs)
  File "/home/6br/anaconda3/envs/toil/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 283, in __init__
    super(AbstractGridEngineBatchSystem, self).__init__(config, maxCores, maxMemory, maxDisk)
  File "/home/6br/anaconda3/envs/toil/lib/python2.7/site-packages/toil/batchSystems/abstractBatchSystem.py", line 310, in __init__
    config, config.maxLocalJobs, maxMemory, maxDisk)
  File "/home/6br/anaconda3/envs/toil/lib/python2.7/site-packages/toil/batchSystems/singleMachine.py", line 134, in __init__
    worker.start()
  File "/home/6br/anaconda3/envs/toil/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
```

Usually, shared cluster machine limits the maximum memory. Toli forked worker threads until the number of threads reaches a certain number, which exceeds the memory limitation. So, it could not start a new thread.
So, I would like to know why so many worker threads should be forked and how to change the number of worker threads. 

The result of top command is following. It exceeds the number of core on our machine(24). 

```
 9585 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:02.07 └─ python sort.py bucket3
 9689 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9688 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9687 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9686 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9685 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9684 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9683 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9682 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9681 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9680 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9679 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9678 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9677 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9676 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9675 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9674 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9673 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9672 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9671 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9670 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9669 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9668 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9667 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9666 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9665 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9664 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9663 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9662 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9661 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9660 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9659 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9658 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9657 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
 9656 6br       20   0 5426M 42328  4836 S  0.0  0.0  0:00.00    ├─ python sort.py bucket3
```

For now, I could run toil with `--maxCores 1`,(it still remained to fork 12 worker threads and it is not fundamental solution.)

## `--gridOption gridEngine`  ignores maxCores option

When I run  `python helloWorld.py bucket --batchSystem gridEngine --maxCores 1`, the same error `thread.error: can't start new thread` occurred. Seemingly, whether or not I use the `maxCores` option, worker threads are forked until the number reaches the maximum threads. So, it causes to raise `thread.error: can't start new thread`.

Currently, I use toil with `--debugWorker` and I succeed to run jobs on the UGE. But it is unnatural.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-319)
┆Issue Number: TOIL-319

**Comment by DailyDreaming** [comment] 2018-08-20 22:39
This looks similar to #2323 where `--maxLocalJobs` isn't doing what it ought to.  Should have a fix soon.

**Comment by bencvdb** [comment] 2018-08-21 17:27
@6br PR #2347 should fix this issue if you specify  `--maxLocalJobs` as needed instead of `--maxCores`. Let me know if this does not fix the problem.

**Comment by DailyDreaming** [comment] 2018-08-23 16:59
#2347 was merged.  Closing this.

Please feel free to reopen if #2347 did not in fact solve the problem.

**Closed by DailyDreaming** 2018-08-23 16:59 UTC

**Comment by 6br** [comment] 2018-08-24 07:55
Thank you!

**Comment by jsmedmar** [comment] 2020-02-19 17:50
Hi All,

`maxLocalJobs` has a contradictory usage in `gridEngine` implementations.

## `maxLocalJobs` determines number of workers in `singleMachine` for `gridEngine` implementations

`maxLocalJobs` is by default set to the number of cpus made available to the Toil head job (which in high cpu machine without proper cgroups configuration might be as high as `32` to `96` cpus):

https://github.com/DataBiosphere/toil/blob/debfc51ab3b0d2a6c56816cd1c4334020ea98b74/src/toil/batchSystems/options.py#L150

https://github.com/DataBiosphere/toil/blob/debfc51ab3b0d2a6c56816cd1c4334020ea98b74/src/toil/lib/threading.py#L109

Importantly, `maxLocalJobs` can also be provided in the command line and is used across batch systems to determine the maximum amount of jobs issued to the scheduler, which can easily be in the thousands:

https://github.com/DataBiosphere/toil/blob/e193fdce9c7a5b36498f1d40475aff04abc35495/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L129-L131

`singleMachine` uses `maxCores` to determine the total amount of threads to be forked to check on jobs:

https://github.com/DataBiosphere/toil/blob/3793c91b639320d03da1634b773774e2f60ebb33/src/toil/batchSystems/singleMachine.py#L96

https://github.com/DataBiosphere/toil/blob/3793c91b639320d03da1634b773774e2f60ebb33/src/toil/batchSystems/singleMachine.py#L58

Here is where the problem arises. For gridEngine implementations, a `localBatch` queue is set as a `singleMachine`, but instead of instantiated with `maxCores` is instantiated with `maxLocalJobs`:

https://github.com/DataBiosphere/toil/blob/3793c91b639320d03da1634b773774e2f60ebb33/src/toil/batchSystems/abstractBatchSystem.py#L334-L336

As explained earlier, `maxLocalJobs` can have values as high as `96` by default and in the thousands when specified. Dividing these numbers by `0.1` (`minCores`) results in thousands of forked threads for `localBatch`.

## Proposed solution

In my opinion, Toil does not need an incredibly high number of worker threads to check on the scheduler. Instead, a default of 10 threads combined with a good `statePollingWait` of 5 to 10 seconds should allow the batch systems to issue thousands of jobs to the scheduler, whilst efficiently checking on jobs. I would suggest either hardcoding the total number of worker threads, or explicitly providing a flag to set the number of worker threads.

If anyone lands here and needs a quick fix to this issue, this is what I did: First, I created a custom `singleMachine` batch system that hardcodes the number of worker threads to `5`:

```python
# single_machine.py

class SingleMachineBatchSystem(SingleMachineBatchSystem):

    """A singleMachine batch system that """

    def __init__(self, config, maxCores, maxMemory, maxDisk):
        """Fake debugWorker and create only 5 threads."""
        config.debugWorker = True

        super(SingleMachineBatchSystem, self).__init__(
            config, maxCores, maxMemory, maxDisk
        )

        for _ in range(5):
            worker = Thread(target=self.worker, args=(self.inputQueue,))
            self.workerThreads.append(worker)
            worker.start()
```

Then, I overwrote the `singleMachine` registry (add this in the top of the script where you import Toil assets):

```python
from . import single_machine

# Toil forks an insane amount of workers in single machine, not needed at all!
registry.addBatchSystemFactory(
    "singleMachine", lambda: single_machine.SingleMachineBatchSystem
)
```

**Comment by adamnovak** [comment] 2020-02-19 18:29
I think what ought to happen is that `--maxLocalJobs` ought to control the maximum number of jobs running on the leader through its singleMachineBatchSystem, and `--maxCores` ought to cap the total number of cores used by active jobs across both batch systems.

**Comment by adamnovak** [comment] 2020-02-19 19:11
The huge number of threads isn't AFAIK to keep an eye on the scheduler, but rather is our system for doing fractional CPU core accounting within the SingleMachineBatchSystem. We want to replace it with something easier on the ulimits (see #2928), but we haven't done it yet.

We might also need something like a `--maxNonLocalJobs` that can be in the thousands, while leaving `--maxLocalJobs` at a sensible number of jobs to run on a single machine.

**Comment by jsmedmar** [comment] 2020-02-19 19:36
Yes `maxCores` is a per job settings, `maxLocalJobs` is a per workflow setting. I just wanted to point out that this was the cause of the `can't start a new thread`. Separating the singleMachine setting from other batch systems seems sensible.
